name: Automatic deploy
on:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: GH_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
