name: Create NPM Package with package.json version
on:
  push:
    branches-ignore:
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Package tag'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta

permissions:
  id-token: write
  contents: write

jobs:
  publish-package:
    name: NPM Package Build and Upload
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Get version from package.json
        id: semver
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Version: $VERSION"
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=semver::${VERSION}"

      - run: npm ci
      - run: npm run build # create the ./dist directory with the files to publish

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ steps.semver.outputs.semver }}$"; then
            echo "Tag v${{ steps.semver.outputs.semver }} already exists."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag v${{ steps.semver.outputs.semver }} does not exist."
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Generate Changelog
        id: changelog
        run: |
          npx auto-changelog -p
          CHANGELOG_CONTENT=$(cat CHANGELOG.md)
          echo $CHANGELOG_CONTENT
          echo "::set-output name=changelog::$CHANGELOG_CONTENT"

      - name: Create Git tag
        if: env.TAG_EXISTS == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.semver.outputs.semver }}
          git push origin v${{ steps.semver.outputs.semver }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

      - name: Create GitHub Release
        if: env.TAG_EXISTS == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.semver.outputs.semver }}
          name: v${{ steps.semver.outputs.semver }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
