name: NPM Package
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
      tag:
        description: 'Package tag'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta

jobs:
  npm-upload:
    name: NPM Package Build and Upload
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
        #   scope: '@stichting-allianceblock-foundation'

      - id: semver
        run: |
          SEMVER="${{ github.event.inputs.version }}"
          if [ -z "$SEMVER" ]; then
            # No manual input, we must be running on a tag
            SEMVER="${GITHUB_REF/refs\/tags\/v/}"
          fi
          echo "::set-output name=semver::${SEMVER}"

      - run: npm ci
      - run: npm version --no-git-tag-version "${{ steps.semver.outputs.semver }}"
      - run: npm run build # create the ./dist directory with the files to publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
